language: node_js
node_js:
- stable
deploy:
  provider: npm
  email: 86287344@qq.com
  skip_cleanup: true
  api_key:
    secure: ocJ0+KRwXPYU/jNbQu/00jVJLp/jP1VziE+BgS7oRWwUH9r5g6Ucvmm1P5AZ+5Dn3OqpaCHYU1XriUQeh1FRlex+esNkFGgAA7yOalexF5iYj7W+g+rJBybcTZCObKvAXJS9EsMX39NjDeizWQQpqkcD1BikPh7fzI88Omk9lHRC87/2gvDI11FaK3LmsTl4YGR3JXVgz65D8a2ti5wkk/wwBwJ1xdmHuzwUefqY3ApdXuhNKC/JeZMLX1unrtVA5aGmkMEv0uOJlh27zvSqoOIjckPU9G8egCFJ4z+/H0EjBeKzw6SERfkvZQq3XsQkct/ufbikG8PA5OmvYJNypm9YVPGMzqxUEwBIXwm6SEI49Epfvww0LtBGhw2Z+CGLxjugQyrRLH7qixekDhZvy0yb8x5qCQGALm8YK0+tQjdajjKakbAAeWtoG2/C2ZZ6fAGNk+fbJrF0MZQEVKDUREOhTk9FZz5yilfclcPCJKj/ruulMfgnsByi8SBEzWUGSQP/gO35RKrHQSV+2D/IKvVMC3b/Rm76TTnqBnwADK2BP7Q7chacHPzOb4B1pL0S/9GB+GxGrAwaQFjcd9bVezsr94GLmZ3Nj9jagCEH7TGYW5Rgxzg/FlbarW2LBQWf8FLVaS175itwKC1nMigKf3eANiOVc3Hxaac+WeYNpT8=
