language: node_js
node_js:
- stable
deploy:
  provider: npm
  email: 86287344@qq.com
  skip_cleanup: true
  api_key:
    secure: BYXmXVERaxu7aDU/CEu2KwCw9SA12Pfp7+KiVsPYRhWvQLV5VQ7rmexZX9leOiqywVdgT5B/QtkVpBesu6pxRfXGomt2R5q+1RS+hkYj/mc9cxHoHD46+Yaq5zBw4ARvCsBsVVuswVfbnEeDJLum4whkRC+FwBOFfD3GsVm8uGU2tPOnt66TqfR3qEJckJ5YBHpuNGPwNndwnrghPrY85zT9N9NpZcH+OzJKpl+xRMxzKBfiODevVk1DNtdwv9csEm/+l1b0cUT1fY+9JX61BAvS3Sc8Ks3d5Tm1NFvPVyq6LkNLgc8sf/OgfOZ9RbHoADUqLZJ1ViXSfVlyu8Y3ljpLljfTEzQyiIbGb+1f91SwHeJVjFIhNJ7fcCJiCfc03LbU/npSUSNhNKiBdPNpStfVS1FKfDjVCDjNGzKbxg7/9GB39wP8vpp6yHIse9sFXptfdcgfXWjgN10lJAYVoLhi7DX8Yks+HuLZReCQ+qp4yEU6GV9tgUv7qn3JvRMeN2vZIglEiIz87LF3MYivR23Kv1Y/IRKV6KtSO1yvul0tW9ZIW1Ma1TZ9dPtB9hACDbMpv++wk+BE7BrCvya7BhLMQSNVxNQ3mG+NwSaw6m51BME32R4AhO80M0HfrBcG5D1xi9/DQ6OO21b4WaR+noIudFMIFwPmkaD/g8YesBU=
